### ISSUE TITLE
Promotion Discount Not Being Included in Transaction Details

### ISSUE THREAD

**Issue by avitus** [spree-contrib/spree_usa_epay#5]
When using a promotional discount I get the following error response from the Gateway:

Gateway Error
  --- !ruby/object:ActiveMerchant::Billing::Response
params: {}
message: !str
  str: Transaction out of balance.
  attributes:
    xsi:type: xsd:string
success: false
test: false
authorization: !!null
fraud_review: !!null
avs_result:
  code: !!null
  message: !!null
  street_match: !!null
  postal_match: !!null
cvv_result:
  code: NO CVV2/CVC DATA AVAILABLE FOR TRANSACTION.
  message: !!null 

According to the gateway documentation that error means:

Transaction does not add up correctly: subtotal + tip + tax + shipping - discount must equal the amount.

Looking at the Spree USA ePay's gateway code (https://github.com/spree/spree_usa_epay/blob/master/lib/spree_usa_epay/client.rb#L160) it seems as though the promotion discount might not be getting sent and hence the equation above doesn't balance.

---

```
def transaction_details(amount, creditcard, gateway_options)
  { 'Description' => gateway_options[:customer],
    'Amount' => double_money(amount),
    'Tax' => double_money(gateway_options[:tax]),
    'Subtotal' => double_money(gateway_options[:subtotal]),
    'Shipping' => double_money(gateway_options[:shipping]),
    'OrderID' => gateway_options[:order_id] }
end
```

---

I took a look at the gateway_options method (https://github.com/spree/spree/blob/8b032c3ab5329bfd0b57597f74bd1549c3328932/core/app/models/creditcard.rb#L214) and it doesn't seem to include the promotional adjustment either. So this would need to be a change there as well.

Hope this is helpful.

**Comment by radar** [comment]
Personally, I can't fix this problem because I don't know what the promotion key should be when it's going to spree_usa_epay. I don't even know where to begin to find that information.

I would think that if you're integrating with this gateway, you would probably know what this parameter is. So if you do know that, please submit a patch that would fix this issue.

Thanks.

**Comment by avitus** [comment]
Radar, it's not the promotion key that's not being sent. It is the amount of the adjustment from the promotion. Looking at this page:

http://wiki.usaepay.com/developer/soap-1.4/objects/transactiondetail

it seems as though the discount amount (from the promotion adjustment) needs to be sent as one of the transaction details. Then the gateway will be happy because

Amount = Subtotal + Tax + Shipping - Discount

It would require a patch to both spree/spree and spree/spree_usa_epay.

I can take a stab at that if you'd like.

**Comment by radar** [comment]
Yes please take a stab at it. I am bogged down with authentication work today and probably tomorrow as well.

**Comment by zeeyang** [comment]
I have a pull req here that fixes the issue from the spree side. We have tested it on our production and it worked well. @avitus can you test it out?

https://github.com/spree/spree/pull/1957

**Comment by radar** [comment]
This pull request has now been pulled into Spree. Thanks!

**Comment by jsqu99** [comment]
This may or may not be the appropriate place for a 'fix', b/c there might be a bigger issue here, but consider this scenario:
- Customer completes an order and payment has not yet been captured
- Customer contacts admin and as a result of the discussion, the admin wants to create an adjustment for whatever reason (they forgot a coupon code, or the customer was unhappy and they give an arbitrary discount)
- Admin attempts to capture payment, but it fails with the "Transaction out of balance" error because this equation is no longer true: Amount = Subtotal + Tax + Shipping - Discount

The reason for this is 'Discount' is wrong.  It is currently computed via this path:

https://github.com/spree/spree/blob/master/core/app/models/spree/payment/processing.rb#L125
https://github.com/spree/spree/blob/master/promo/app/models/spree/order_decorator.rb#L17
https://github.com/spree/spree/blob/master/promo/app/models/spree/adjustment_decorator.rb#L4

The last line is significant in that it picks up ":originator_type => 'Spree::PromotionAction'", but adjustments created from the admin app have a nil originator, so they are not treated as 'discounts'.

I'm wondering if we should change: https://github.com/spree/spree/blob/master/core/app/models/spree/payment/processing.rb#L125

to some bastardized collection of adjustments (discount + all adjustments that have a null originator)?

Thoughts?

**Comment by jsqu99** [comment]
Changing order#promo_total to:

```
  def promo_total
    arel = Spree::Adjustment.arel_table
    arel_clause = arel[:originator_type].
      eq('Spree::PromotionAction').
      or(arel[:originator_type].eq(nil))

    adjustments.eligible.where(arel_clause).map(&:amount).sum
  end
```

seems to do the trick.
